(function(){
'use strict';
var modules=[['home','⌂','Inicio','index.html'],['archive','⌘','Archive','archive.html'],['progress','◎','Radar','progress.html'],['pokedex','▣','Pokédex','pokedex.html'],['atlas','◉','Atlas','atlas.html'],['skills','⌁','Skills','skill-tree.html'],['map','◇','Mapa','world-map.html'],['timeline','↟','Timeline','timeline.html'],['hall','★','Trofeos','hall-of-fame.html'],['lab','∆','Lab','laboratory.html']];
var module=document.documentElement.getAttribute('data-odedex-module')||document.body&&document.body.dataset.module||'';
function dock(){var d=document.createElement('nav');d.className='odedex-dock';d.setAttribute('aria-label','Módulos ODEDEX');d.innerHTML=modules.map(function(m){return '<a href="'+m[3]+'" class="'+(m[0]===module?'is-active':'')+'" title="Alt+'+(modules.indexOf(m)+1)+' · '+m[2]+'"><b>'+m[1]+'</b><span>'+m[2]+'</span></a>'}).join('');document.body.appendChild(d);var p=document.createElement('div');p.className='odedex-context-pill';p.id='odedexContextPill';document.body.appendChild(p);renderPill();}
function renderPill(){var p=document.getElementById('odedexContextPill');if(!p||!window.ODEDEX)return;var c=ODEDEX.loadContext(),r=ODEDEX.byId(c.selectedId),text=r?'CONTEXTO // '+r.id+' · C'+r.chapter+'.S'+r.section+' · '+(c.competency?ODEDEX.label(c.competency):ODEDEX.label(r.competencies[0]||'')):'CONTEXTO // sin ficha seleccionada';if(p.textContent!==text)p.textContent=text;}
function setFromId(id){if(!window.ODEDEX||!id)return;var r=ODEDEX.byId(id),c=ODEDEX.loadContext();if(r&&(c.selectedId!==r.id||c.chapter!==r.chapter||c.section!==r.section))ODEDEX.updateContext({selectedId:r.id,chapter:r.chapter,section:r.section,competency:r.competencies[0]||''});}
function bridgeClick(e){var t=e.target.closest('[data-id],[data-record],[data-chapter],[data-competency],[data-node]');if(!t||!window.ODEDEX)return;var id=t.dataset.id||t.dataset.record;if(id)setFromId(id);var part={};if(t.dataset.chapter)part.chapter=+t.dataset.chapter;if(t.dataset.competency)part.competency=t.dataset.competency;if(t.dataset.node&&/^\d+$/.test(t.dataset.node))part.section=+t.dataset.node;else if(t.dataset.node&&ODEDEX.labels[t.dataset.node])part.competency=t.dataset.node;if(Object.keys(part).length)ODEDEX.updateContext(part);}
function observe(){var mo=new MutationObserver(function(){var t=document.querySelector('.record-row.is-selected[data-id],.dex-row.selected[data-id],[aria-selected="true"][data-id]');if(t)setFromId(t.dataset.id);renderPill();});mo.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class','aria-selected']});}
function restore(){if(!window.ODEDEX)return;var c=ODEDEX.loadContext();if(module==='archive'&&c.selectedId){var tries=0,tm=setInterval(function(){var row=document.querySelector('.record-row[data-id="'+CSS.escape(c.selectedId)+'"]');if(row){row.click();row.scrollIntoView({block:'center'});clearInterval(tm)}else if(++tries>30)clearInterval(tm)},100)}
if(module==='progress'){var tries2=0,tm2=setInterval(function(){var b=document.querySelector('[data-chapter="'+c.chapter+'"]');if(b){b.click();if(c.section){setTimeout(function(){var n=document.querySelector('[data-node="'+c.section+'"]');if(n)n.dispatchEvent(new MouseEvent('click',{bubbles:true}));if(c.competency)setTimeout(function(){var cp=document.querySelector('[data-competency="'+CSS.escape(c.competency)+'"]');if(cp)cp.click()},140)},120)}clearInterval(tm2)}else if(++tries2>30)clearInterval(tm2)},100)}}
function switcher(){var el=document.createElement('div');el.className='odedex-switcher';el.hidden=true;el.innerHTML='<div class="odedex-switcher-card"><h2>ODEDEX // cambiar módulo</h2><div class="odedex-switcher-grid">'+modules.map(function(m,i){return '<a href="'+m[3]+'"><b>'+((i+1)%10)+'</b> · '+m[2]+'</a>'}).join('')+'</div></div>';document.body.appendChild(el);el.addEventListener('click',function(e){if(e.target===el)el.hidden=true});document.addEventListener('keydown',function(e){var typing=/INPUT|TEXTAREA|SELECT/.test((e.target&&e.target.tagName)||'');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();el.hidden=!el.hidden}if(e.key==='Escape'&&!el.hidden)el.hidden=true;if(e.key==='?'&&!typing&&['archive','pokedex'].indexOf(module)===-1){e.preventDefault();el.hidden=!el.hidden}if(e.altKey&&!typing&&/^[0-9]$/.test(e.key)){var n=+e.key,idx=n===0?9:n-1;if(idx>=0&&idx<modules.length){e.preventDefault();location.href=modules[idx][3]}}});}
function themeToggle(){if(!window.ODEDEX_THEME)return;var b=document.createElement('button');b.className='theme-toggle';b.type='button';b.setAttribute('aria-live','polite');function paint(){var theme=document.documentElement.dataset.theme==='radar'?'radar':'archive',next=theme==='radar'?'Dark':'Light';b.innerHTML='<span class="theme-toggle-icon" aria-hidden="true">'+(theme==='radar'?'◐':'◑')+'</span><span class="theme-toggle-label">'+next+'</span>';b.setAttribute('aria-label','Cambiar a modo '+next);b.title='Cambiar a modo '+next}b.addEventListener('click',function(){window.ODEDEX_THEME.toggle();paint()});window.addEventListener('odedex:theme',paint);document.body.appendChild(b);paint()}
document.addEventListener('DOMContentLoaded',function(){dock();switcher();themeToggle();if(['archive','progress','pokedex'].indexOf(module)!==-1){document.addEventListener('click',bridgeClick,true);observe();setTimeout(restore,50)}window.addEventListener('odedex:context',renderPill);window.addEventListener('storage',renderPill)});
}());
